### PR TITLE
add conda param bitNo

### PR DESCRIPTION
**Pull request by mrchypark**
and roxygen2 version 6.0.1 to 6.1.0

### CODE REVIEW

**Comment by talgalili** [comment]
Thanks for the diff,
I see travis is still complaining the following:

```
0.42schecking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'install.conda'
  ‘bitNo’
Documented arguments not in \usage in documentation object 'install.conda':
  ‘binNo’
Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.checking Rd cross-references ... NOTE
Package unavailable to check Rd xrefs: ‘R.utils’
```

Could you please fix and re-submit?

**Comment by mrchypark** [comment]
fix typo too... TT and java documents are not complete. so fix too.

**Comment by talgalili** [comment]
Much appreciated, thanks.
Lastly, could you update the NEWS and DESCRIPTION files?
https://github.com/talgalili/installr/blob/master/NEWS
https://github.com/talgalili/installr/blob/master/DESCRIPTION

(this patch could be installr 0.21.1)

**Comment by mrchypark** [comment]
@talgalili update like this?

**Comment by talgalili** [comment]
Yes, thanks :)

**Pull request merged**
