### PR TITLE
add install java for window using openjdk support version 9, 10

### PR DESCRIPTION
**Pull request by mrchypark**

### CODE REVIEW

**Comment by talgalili** [comment]
Cool, thanks!
It would take me more than a week to review. But I'll look at it.

**Comment by mrchypark** [comment]
any progress here?

**Comment by talgalili** [comment]
Thanks for the ping. I'll try to do it this week...

**Comment by mrchypark** [comment]
never mind. 
I fully understand what means to maintain the package.
I don't want to rush you. ;)

**Comment by talgalili** [comment]
This commit has several issues with documentation, I've merged it, I'll make a few fixes and then will push it back.

**Comment by talgalili** [comment]
Fixed (although I may wait a bit before pushing this to CRAN)

**Pull request merged**
