### PR TITLE
fix to is.x64()

### PR DESCRIPTION
**Pull request by ajrgodfrey**
The details for "release" for the latest x64 version I used were different to the text specified in the is.x64() function. I altered it to hopefully is more future proof. You may decide not to allow the suggested change to the install.python() function but I think this should become the standard from here on, so that  the 32bit user has to take action, which should be extremely rare nowadays.

### CODE REVIEW

**Comment by talgalili** [comment]
Hey, could you please update the NEWS file and DESCRIPTION? (also, please make sure to pull the recent version before merging)

**Comment by talgalili** [comment]
ping?

**Comment by ajrgodfrey** [comment]
Having to check a few things.

**Comment by talgalili** [comment]
Thanks - merged.

**Pull request merged**
