### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by Bisaloo**

### CODE REVIEW

**Comment by talgalili** [comment]
Great job, Thanks!
Did you do it manually? (or with some automated code?)

Merged.

**Comment by Bisaloo** [comment]
I noticed one typo while checking the documentation. So I checked the whole package with `spelling::spell_check_package()` and fixed the most obvious ones. I think there are still a couple of them in NEWS for example

**Comment by talgalili** [comment]
Very cool, thanks!
Any chance you'll give a look also at the dendextend and heatmaply repos?

**Comment by Bisaloo** [comment]
Probably not anytime soon, sorry.

**Comment by talgalili** [comment]
Fair enough :)
Thanks for what you've done already!

**Pull request merged**
