### PR TITLE
update install.Rtools to v42

### LINKED ISSUE #177: install.RTools error
**Describe the bug**
The installer URL is a 404.

**To Reproduce**

`installr::install.Rtools()`

Session output: 
```
> installr::install.Rtools()
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 4.2.1 was found. (Only the following incompatible version(s) of Rtools were found: 4.0)

Please download and install Rtools 4.2 from https://cran.r-project.org/bin/windows/Rtools/ or https://www.r-project.org/nosvn/winutf8/ucrt3/.
trying URL 'https://cran.r-project.org/bin/windows/Rtools/rtools42-x86_64.exe'

Explanation of the error: You didn't enter a valid .EXE URL. 
This is likely to have happened because there was a change in the URL of the installer file in the download page of the software (making our function unable to know what to download). 

This might have already been fixed in the latest version of installr. Install the latest version of installr using devtools::install_github('talgalili/installr') and try again.

If this doesn't help please e-mail: tal.galili@gmail.com and let me know this function needs updating/fixing (please include the output of sessionInfo() ) - thanks!

We failed to download the file into:
 Z:/RTemp\RtmpOctzSD/rtools42-x86_64.exe 
(i.e.: the installation failed)
Warning messages:
1: In download_fun(exe_URL, destfile = exe_filename, quiet = FALSE,  :
  the 'wininet' method is deprecated for http:// and https:// URLs
2: In download_fun(exe_URL, destfile = exe_filename, quiet = FALSE,  :
  cannot open URL 'https://cran.r-project.org/bin/windows/Rtools/rtools42-x86_64.exe': HTTP status was '404 Not Found'
```

Thank you!

### PR DESCRIPTION
**Pull request by arthurgailes**
Closes https://github.com/talgalili/installr/issues/177

### CODE REVIEW

**Comment by arthurgailes** [comment]
I don't know much about their build number syntax, so its possible this could fail on future versions.

**Comment by burgerga** [comment]
Thanks for this! However, 

```r
> get_rtools_url("4.2")
https://cran.r-project.org/bin/windows/Rtools/rtools42/files/rtools42-rtools42-5355-5357.exe
```

is not the right path. I think the problem is that file_suffix actually contains the full filename. I think that would actually be nice to get the full filename here, maybe with this regex:

```
str_match(html_string, pattern = "href=\"(rtools.*\\.exe)\"")[,2]
```

then `filename` becomes a bit simpler. What do you think?

**Comment by arthurgailes** [comment]
That seems more complicated to me than just removing the duplicate r version insert, done here, but feel free to change if you prefer.

**Comment by burgerga** [comment]
Much appreciated! I don't know when there will be another CRAN release, @talgalili is the only one who can do that.

**Comment by talgalili** [comment]
Thanks @burgerga and @arthurgailes  - installr version 0.23.4 is now submitted to CRAN.
It took a bit longer than I wanted since an earlier submission as is had some notes/warnings (unrelated to this PR), which I had to resovle before I could submit.
I expect the package to be in CRAN within ~48 hours.

I've made sure that both of you are mentioned as contributors in the DESCRIPTION (and in the NEWS).

Thanks again for taking care of this!

**Comment by arthurgailes** [comment]
Thank you.

**Pull request merged**
