### PR TITLE
fix #137 : add appveyor integration

### LINKED ISSUE #137: Add Appveyor integration
**Is your feature request related to a problem? Please describe.**
There are currently no automated tests in `installr`.

I am trying to fix a bug with `create.global.library` (https://github.com/talgalili/installr/pull/136) and have introduced some testthat tests; these tests are skipped during CI on Travis because installr is pinned to Windows (by OS_type: windows in the DESCRIPTION) and Travis is an Ubuntu-based system. 

As such I'd like to add appveyor integration so that any tests can be ran (on a windows setup) whenever anyone pushes to installr on github.

**Describe the solution you'd like**
I would like to add appveyor integration. This will require that @talgalili (or another maintainer) open an Appveyor account and link installr to that account (details here: https://bookdown.org/rdpeng/RProgDA/continuous-integration.html and here: https://github.com/krlmlr/r-appveyor/blob/master/README.md). Once that's done I'm happy to push a PR that adds appveyor integration.

**Describe alternatives you've considered**
I'm not aware of any other windows-based CI solutions for which there is good tools for R packages.

**Additional context**

### PR DESCRIPTION
**Pull request by russHyde**
# Description

This sets up a Windows-based CI platform for `installr` so that `R CMD check` and automated tests can be ran whenever someone makes a pull request.

Fixes #137 

## Type of change

New feature (non-breaking change which adds functionality)
- No source-code changes are introduced by this change-set

## Changes

- Appveyor config was created using `usethis::use_appveyor()`
- Appveyor badge was added to the README
- [Minor] Added 'R.utils' package to `DESCRIPTION::Suggests` since it was required for documentation cross-refs during R CMD check on appveyor and travis.

### CODE REVIEW

**Comment by russHyde** [comment]
NOTEs during the appveyor build:

~~~~
* checking Rd line widths ... NOTE
Rd file 'install.GraphicsMagick.Rd':
  \usage lines wider than 90 characters:
       install.GraphicsMagick(URL = "https://sourceforge.net/projects/graphicsmagick/files/latest/download",
These lines will be truncated in the PDF manual.
* checking Rd cross-references ... NOTE
Package unavailable to check Rd xrefs: 'R.utils'
~~~~

**Comment by russHyde** [comment]
TODO: 
- [ ] flatten the commits
- [ ] notify maintainer

**Comment by talgalili** [comment]
Thanks. Please also make sure to update the NEWS file (NOT NEWS.md). And
also DESCRIPTION.

**Comment by russHyde** [comment]
No problem. All the best

**Comment by talgalili** [comment]
Cool. Is the diff ready for merging?

**Comment by russHyde** [comment]
Yes. Feel free to merge it whenever

**Comment by logworthy** [comment]
Some AppVeyor builds seem to be failing due to timeouts while downloading packages:
https://ci.appveyor.com/project/talgalili/installr/builds/28815256#L201
https://ci.appveyor.com/project/talgalili/installr/builds/28816980#L196

Not sure if there is anything we can do about it here, but I've added an issue on the remotes repo:
https://github.com/r-lib/remotes/issues/454

**Comment by russHyde** [comment]
That looks like a server problem. I can't access the "https://cloud.r-project.org/bin/windows/contrib/3.6/" folder but I can access "https://cloud.r-project.org/bin/windows/contrib/3.7/" (for example). There's probably just a lot of traffic at the moment.

**Pull request merged**
